// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: favorites.sql

package db

import (
	"context"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, recipe_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID   int64 `json:"user_id"`
	RecipeID int64 `json:"recipe_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.RecipeID)
	return err
}

const countFavoritesByUser = `-- name: CountFavoritesByUser :one
SELECT count(*)::bigint
FROM favorites
WHERE user_id = $1
`

func (q *Queries) CountFavoritesByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFavoritesByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS(
  SELECT 1 FROM favorites
  WHERE user_id = $1 AND recipe_id = $2
)
`

type IsFavoriteParams struct {
	UserID   int64 `json:"user_id"`
	RecipeID int64 `json:"recipe_id"`
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.UserID, arg.RecipeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavoriteRecipesByUser = `-- name: ListFavoriteRecipesByUser :many
SELECT
  r.id,
  r.title,
  r.image,
  r.summary,
  r.source_url,
  r.prep_time_minutes,
  r.cook_time_minutes,
  r.serves,
  r.ingredients,
  r.preparation,
  r.tags
FROM favorites f
JOIN recipes r ON r.id = f.recipe_id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFavoriteRecipesByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFavoriteRecipesByUser(ctx context.Context, arg ListFavoriteRecipesByUserParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listFavoriteRecipesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Image,
			&i.Summary,
			&i.SourceUrl,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.Serves,
			&i.Ingredients,
			&i.Preparation,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 AND recipe_id = $2
`

type RemoveFavoriteParams struct {
	UserID   int64 `json:"user_id"`
	RecipeID int64 `json:"recipe_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.RecipeID)
	return err
}
