// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddFavorite(ctx context.Context, arg AddFavoriteParams) error
	CountFavoritesByUser(ctx context.Context, userID int64) (int64, error)
	CountRecipes(ctx context.Context, q_ pgtype.Text) (int64, error)
	CountRecipesByCategoryName(ctx context.Context, arg CountRecipesByCategoryNameParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetRecipeByID(ctx context.Context, id int64) (Recipe, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListFavoriteRecipesByUser(ctx context.Context, arg ListFavoriteRecipesByUserParams) ([]Recipe, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error)
	ListRecipesByCategoryName(ctx context.Context, arg ListRecipesByCategoryNameParams) ([]Recipe, error)
	RecipeExists(ctx context.Context, id int64) (bool, error)
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	RevokeAllRefreshTokensForUser(ctx context.Context, userID int64) error
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error
}

var _ Querier = (*Queries)(nil)
