// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecipes = `-- name: CountRecipes :one
SELECT count(*)::bigint
FROM recipes r
WHERE ($1::text IS NULL OR r.title ILIKE ('%' || $1 || '%'))
`

func (q *Queries) CountRecipes(ctx context.Context, q_ pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipes, q_)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecipesByCategoryName = `-- name: CountRecipesByCategoryName :one
SELECT count(*)::bigint
FROM recipes r
JOIN recipe_categories rc ON rc.recipe_id = r.id
JOIN categories c ON c.id = rc.category_id
WHERE c.name = $1
  AND ($2::text IS NULL OR r.title ILIKE ('%' || $2 || '%'))
`

type CountRecipesByCategoryNameParams struct {
	Name string      `json:"name"`
	Q    pgtype.Text `json:"q"`
}

func (q *Queries) CountRecipesByCategoryName(ctx context.Context, arg CountRecipesByCategoryNameParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipesByCategoryName, arg.Name, arg.Q)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT
  id,
  title,
  image,
  summary,
  source_url,
  prep_time_minutes,
  cook_time_minutes,
  serves,
  ingredients,
  preparation,
  tags
FROM recipes
WHERE id = $1
`

func (q *Queries) GetRecipeByID(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Image,
		&i.Summary,
		&i.SourceUrl,
		&i.PrepTimeMinutes,
		&i.CookTimeMinutes,
		&i.Serves,
		&i.Ingredients,
		&i.Preparation,
		&i.Tags,
	)
	return i, err
}

const listRecipes = `-- name: ListRecipes :many
SELECT
  r.id,
  r.title,
  r.image,
  r.summary,
  r.source_url,
  r.prep_time_minutes,
  r.cook_time_minutes,
  r.serves,
  r.ingredients,
  r.preparation,
  r.tags
FROM recipes r
WHERE ($2::text IS NULL OR r.title ILIKE ('%' || $2 || '%'))
  AND ($3::bigint IS NULL OR r.id > $3::bigint)
ORDER BY r.id
LIMIT $1
`

type ListRecipesParams struct {
	Limit  int32       `json:"limit"`
	Q      pgtype.Text `json:"q"`
	LastID pgtype.Int8 `json:"last_id"`
}

func (q *Queries) ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipes, arg.Limit, arg.Q, arg.LastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Image,
			&i.Summary,
			&i.SourceUrl,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.Serves,
			&i.Ingredients,
			&i.Preparation,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByCategoryName = `-- name: ListRecipesByCategoryName :many
SELECT
  r.id,
  r.title,
  r.image,
  r.summary,
  r.source_url,
  r.prep_time_minutes,
  r.cook_time_minutes,
  r.serves,
  r.ingredients,
  r.preparation,
  r.tags
FROM recipes r
JOIN recipe_categories rc ON rc.recipe_id = r.id
JOIN categories c ON c.id = rc.category_id
WHERE c.name = $1
  AND ($3::text IS NULL OR r.title ILIKE ('%' || $3 || '%'))
  AND ($4::bigint IS NULL OR r.id > $4::bigint)
ORDER BY r.id
LIMIT $2
`

type ListRecipesByCategoryNameParams struct {
	Name   string      `json:"name"`
	Limit  int32       `json:"limit"`
	Q      pgtype.Text `json:"q"`
	LastID pgtype.Int8 `json:"last_id"`
}

func (q *Queries) ListRecipesByCategoryName(ctx context.Context, arg ListRecipesByCategoryNameParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipesByCategoryName,
		arg.Name,
		arg.Limit,
		arg.Q,
		arg.LastID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Image,
			&i.Summary,
			&i.SourceUrl,
			&i.PrepTimeMinutes,
			&i.CookTimeMinutes,
			&i.Serves,
			&i.Ingredients,
			&i.Preparation,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recipeExists = `-- name: RecipeExists :one
SELECT EXISTS(SELECT 1 FROM recipes WHERE id = $1)
`

func (q *Queries) RecipeExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, recipeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
